### ISSUE TITLE
Failing to apply steam tdp and gpu clocks

### ISSUE THREAD

**Issue by adolfotregosa** [corando98/steam-patch#7]
![20231114_192831](https://github.com/corando98/steam-patch/assets/7437931/0535ee6c-7c0d-4dfd-89e9-fe49ae1fb79e)

https://youtu.be/DhEnhmet1KM?si=aBinLOMDpm42jUsk

I can try going to desktop and back or restart the ally and it will eventually work.

If I restart service it starts working. 

How can I help? I'm using steam stable and only steam-patch

**Comment by corando98** [comment]
This message is typically found when steam-patch can not connect to steam, ensure that you have the following file. "$HOME/.steam/steam/.cef-enable-remote-debugging", you could also check by going into steam settings, enable developer, and ensure that cef remote debugging is enabled.

Also, I noticed that you are using Manjaro, this has been tested with Nobara and Chimera. You might have to check that the paths are correct as I am not sure how steam is installed into your OS.

**Comment by adolfotregosa** [comment]
This is how I fix it. https://youtu.be/ezD5yZQd02M

I think I found a way to replicate it. After I restart service and it starts working I can reboot ally, restart steam, go to desktop ,etc ,etc. If I shutdown ally from sddm or kde there's no problem but if I shutdown from steam on the next boot the issue is there. Does this make any sense or was it a coincidence ?

EDIT: it was a coincidence. I have no idea why it breaks but it breaks randomly 

Steam was installed from manjaro official repositories. The folder seams to be stock folder. Like I said if I restart service it starts working

**Comment by corando98** [comment]
I would need more logs to replicate, if you can find a way to replicate this consistently I can look into it

**Comment by adolfotregosa** [comment]
> I would need more logs to replicate, if you can find a way to replicate this consistently I can look into it

As far I can tell If I shutdown seams fastest way to make it happen.. For me the steam icon changes, side key works but tdp and gpu don't get patched. Can you somehow maybe slow down the patching?

**Comment by adolfotregosa** [comment]
Ok. I know WHEN if fails by looking at the Xbox / steam icon. When steam starts and there's a xbox icon, it failed to apply.

Have a look at this -> https://youtu.be/I5V5YVU2Pkg

**Comment by corando98** [comment]
There are two things happening here: 

1. Steam button logo change when using special keys: The method used by steam-patch to send the QAM and Steam Menu is by attaching itself to a function call that a Steamdeck would send, hence why you see the Steamdeck 'Steam' logo.

2. This is different from patching, if you see that the Logo reverts back when using the regular controls, TDP/GPU slider is reverted. This is an indication that patching was not successful. 

This can happen due to:
1. The chunk~.js file we are patching was already patched

Can you either do ```journalctl -u --follow steam-patch``` then restart steam and send the log produced here?

To give you an idea on point 1, and why it wouldn't patch, we use a "find_text_to_replace" then a "text_to_replace", so when we swap these in a previous run of steampatch, we do not track these changes for the next time. So next time steampatch runs, it will not patch because those changes it is expecting are already there. Even more if the user was changing the config file, meaning that the previous value is never the same. 

This can be mitigated in a future update, where I keep track of a ".patched" file when patched, and if on unexpected exit of steampatch we can use as a check that steam-patch was previously patched.

**Comment by adolfotregosa** [comment]
ok I was lucky. log should have before with patch failed and after with patch successful.

[steam-patch-log.txt](https://github.com/corando98/steam-patch/files/13366815/steam-patch-log.txt)

Looking at the logs, the patch is not applied on the first steam boot, I am missing "Applying patch: Patch......" etc

**Comment by corando98** [comment]
@adolfotregosa So the first time it always fails, then after a restart of steam-patch it patches correctly? Is your language set to anything other than English US?

**Comment by adolfotregosa** [comment]
> @adolfotregosa So the first time it always fails, then after a restart of steam-patch it patches correctly? Is your language set to anything other than English US?

I was lucky when saving that log. Sometimes I can restart steam 10 times and tdp and gpu won't change but when creating the log restarting steam it did work correctly.

Restarting service makes it work correctly, always, yes.
Language is set to English.
